# Generated by Django 3.1.2 on 2020-10-23 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('stock', models.CharField(max_length=300, verbose_name='Piezas')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Precio')),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
    ]
