# Generated by Django 3.1.2 on 2020-10-29 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20201023_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Cliente')),
                ('stock', models.CharField(max_length=300, verbose_name='Piezas')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total')),
                ('articulo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.articulo', verbose_name='Articulo')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Carrito',
            },
        ),
    ]
