# Generated by Django 3.1.2 on 2020-10-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_venta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name': 'Venta', 'verbose_name_plural': 'Nueva Venta'},
        ),
        migrations.AlterField(
            model_name='venta',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre Cliente'),
        ),
    ]
